server:
  port: 8082

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 4 # 连接池最大空闲连接
        min-idle: 1 # 连接池最小空闲连接
        max-wait: 2000ms # 获取连接的最大等待时间

logging:
  config: classpath:log4j2.xml
  level:
    root: debug
    me.yangjun.study.spring2025004: debug


